services:

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    env_file:
      - ./backend/.env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - project_network


  backend:
    build:
      context: ./backend
    container_name: server
    volumes:
      - ./backend/uploads:/backend/uploads
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - project_network


  frontend:
    build:
      context: ./frontend
    container_name: frontend
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    networks:
      - project_network

networks:
  project_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local