services:

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    env_file:
      - ./backend/.env.development.local
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - project_network


  backend:
    image: akbarihossein/mathbot-server:1.0.3
    container_name: server
    env_file:
      - ./backend/.env.development.local
    command: gunicorn --bind 0.0.0.0:8000 server.wsgi:application
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - project_network


  frontend:
    image: akbarihossein/mathbot:1.0.3
    container_name: frontend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "3000:3000"
    networks:
      - project_network


  nginx:
    image: nginx:stable-alpine
    container_name: nginx_container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - project_network

volumes:
  mysql_data:

networks:
  project_network:
    driver: bridge
