services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    networks:
      - project_network


  backend:
    image: akbarihossein/mathbot-server:1.0.3.2
    container_name: server
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - project_network


  frontend:
    image: akbarihossein/mathbot:1.0.3.1
    container_name: frontend
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    networks:
      - project_network

networks:
  project_network:
    driver: bridge
